# -*- coding: utf-8 -*-
"""Sales Data Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WlrqSK0dgRl5vbdhWp2Q8Mt3tTbK1cP6
"""

import pandas as pd
import numpy as np
import io

# The data is assumed to be loaded from the canvas environment.
# Define the filename provided in the context.
FILE_NAME = "sales_record.csv"

# --- 1. Load the dataset into a DataFrame and display the first 5 rows. ---
try:
    # Read the CSV file into a DataFrame
    df = pd.read_csv(FILE_NAME)
    print("--- 1. Loaded DataFrame (First 5 Rows) ---")
    print(df.head())
    print("-" * 50)

except FileNotFoundError:
    print(f"Error: The file '{FILE_NAME}' was not found. Please ensure it is correctly uploaded.")
    exit()
except Exception as e:
    print(f"An error occurred during file loading: {e}")
    exit()

# --- 2. Show general info (.info()) and summary statistics (.describe()). ---
print("--- 2a. General Info (.info()) ---")
df.info()
print("-" * 50)

print("--- 2b. Summary Statistics (.describe()) ---")
print(df.describe(include='all'))
print("-" * 50)

# --- 3. List all unique values in Region, Country, Item Type, Sales Channel, and Order Priority. ---
unique_cols = ['Region', 'Country', 'Item Type', 'Sales Channel', 'Order Priority']
print("--- 3. Unique Values in Key Columns ---")
for col in unique_cols:
    print(f"\nUnique values in '{col}':")
    # Limiting the display of unique countries for brevity if there are too many
    if col == 'Country':
        print(df[col].unique()[:5].tolist(), '... (first 5)')
    else:
        print(df[col].unique().tolist())
print("-" * 50)

# --- 4. Count the total number of sales records. ---
total_records = len(df)
print(f"--- 4. Total Number of Sales Records: {total_records} ---")
print("-" * 50)

# --- 5. Filter all orders where Region is “Sub-Saharan Africa” and Sales Channel is “Online”. ---
filter_mask_5 = (df['Region'] == 'Sub-Saharan Africa') & (df['Sales Channel'] == 'Online')
df_filtered_5 = df[filter_mask_5]
print("--- 5. Orders Filtered: Region='Sub-Saharan Africa' & Sales Channel='Online' ---")
print(f"Total matching orders: {len(df_filtered_5)}")
print("-" * 50)

# --- 6. Display only Country, Item Type, and Units Sold for those filtered rows. ---
df_display_6 = df_filtered_5[['Country', 'Item Type', 'Units Sold']]
print("--- 6. Country, Item Type, and Units Sold for Filtered Orders (First 5 Rows) ---")
print(df_display_6.head())
print("-" * 50)

# --- 7. Find all high-priority (Order Priority == 'H') orders with Units Sold greater than 5000. ---
filter_mask_7 = (df['Order Priority'] == 'H') & (df['Units Sold'] > 5000)
df_filtered_7 = df[filter_mask_7]
print("--- 7. High-Priority Orders ('H') with Units Sold > 5000 (First 5 Rows) ---")
print(df_filtered_7[['Order ID', 'Country', 'Units Sold']].head())
print(f"Total matching high-priority orders > 5000 units: {len(df_filtered_7)}")
print("-" * 50)

# --- 8. Convert Order Date and Ship Date to datetime format. ---
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])
print("--- 8. Date Columns Converted to Datetime Format ---")
df.info(verbose=False) # Check dtypes quickly
print("-" * 50)

# --- 9. Filter all orders where the shipping delay (Ship Date - Order Date) is more than 10 days. ---
df['Shipping Delay'] = df['Ship Date'] - df['Order Date']
delay_threshold = pd.Timedelta(days=10)
df_long_delay = df[df['Shipping Delay'] > delay_threshold]
print("--- 9. Orders with Shipping Delay > 10 Days (First 5 Rows) ---")
print(df_long_delay[['Order ID', 'Order Date', 'Ship Date', 'Shipping Delay']].head())
print(f"Total orders with > 10 day delay: {len(df_long_delay)}")
print("-" * 50)

# --- 10. Create new column Total Revenue = Units Sold × Unit Price. ---
df['Total Revenue'] = df['Units Sold'] * df['Unit Price']

# --- 11. Create another column Total Cost = Units Sold × Unit Cost. ---
df['Total Cost'] = df['Units Sold'] * df['Unit Cost']

# --- 12. Create a column Profit = Total Revenue – Total Cost. ---
df['Profit'] = df['Total Revenue'] - df['Total Cost']

# --- 13. Create a column Profit Margin (%) = (Profit / Total Revenue) × 100, rounded to 2 decimals. ---
# Handle potential division by zero for Total Revenue = 0 (though unlikely in this dataset)
df['Profit Margin (%)'] = np.where(df['Total Revenue'] > 0,
                                   (df['Profit'] / df['Total Revenue']) * 100, 0).round(2)
print("--- 10-13. New Financial Columns Created (Check first row for values) ---")
print(df[['Units Sold', 'Unit Price', 'Unit Cost', 'Total Revenue', 'Total Cost', 'Profit', 'Profit Margin (%)']].head(1))
print("-" * 50)

# --- 14. Compute total revenue per Region. ---
revenue_per_region = df.groupby('Region')['Total Revenue'].sum().sort_values(ascending=False)
print("--- 14. Total Revenue Per Region ---")
print(revenue_per_region)
print("-" * 50)

# --- 15. Compute average profit per Item Type. ---
avg_profit_per_item = df.groupby('Item Type')['Profit'].mean().sort_values(ascending=False).round(2)
print("--- 15. Average Profit Per Item Type ---")
print(avg_profit_per_item)
print("-" * 50)

# --- 16. Find the most sold Item Type (by total Units Sold). ---
most_sold_item = df.groupby('Item Type')['Units Sold'].sum().sort_values(ascending=False).index[0]
most_sold_units = df.groupby('Item Type')['Units Sold'].sum().max()
print(f"--- 16. Most Sold Item Type: {most_sold_item} (Total Units Sold: {most_sold_units:,.0f}) ---")
print("-" * 50)

# --- 17. Find the top 3 Country values by total Profit. ---
top_3_countries = df.groupby('Country')['Profit'].sum().nlargest(3).round(2)
print("--- 17. Top 3 Countries by Total Profit ---")
print(top_3_countries)
print("-" * 50)

# --- 18. For each Sales Channel, compute average Units Sold, total Revenue, and total Profit. ---
sales_channel_summary = df.groupby('Sales Channel').agg(
    Average_Units_Sold=('Units Sold', 'mean'),
    Total_Revenue=('Total Revenue', 'sum'),
    Total_Profit=('Profit', 'sum')
).round(2)
print("--- 18. Summary Metrics Per Sales Channel ---")
print(sales_channel_summary)
print("-" * 50)

# --- 19. Sort all records by Order Date in ascending order and show the first and last 10 rows. ---
df_sorted_date = df.sort_values(by='Order Date', ascending=True)
print("--- 19. Records Sorted by Order Date (First 10 Rows) ---")
print(df_sorted_date[['Order Date', 'Country', 'Total Profit']].head(10))
print("\n--- 19. Records Sorted by Order Date (Last 10 Rows) ---")
print(df_sorted_date[['Order Date', 'Country', 'Total Profit']].tail(10))
print("-" * 50)

# --- 20. Extract Year and Month from Order Date into new columns. ---
df['Order Year'] = df['Order Date'].dt.year
df['Order Month'] = df['Order Date'].dt.month
print("--- 20. Extracted Year and Month Columns (First 5 Rows) ---")
print(df[['Order Date', 'Order Year', 'Order Month']].head())
print("-" * 50)

# --- 21. Group by Year and find total Revenue and total Units Sold per year. ---
yearly_summary = df.groupby('Order Year').agg(
    Total_Revenue=('Total Revenue', 'sum'),
    Total_Units_Sold=('Units Sold', 'sum')
).round(2)
print("--- 21. Total Revenue and Units Sold Per Year ---")
print(yearly_summary)
print("-" * 50)

# --- 22. Find which month (across all years) had the highest average Profit. ---
monthly_avg_profit = df.groupby('Order Month')['Profit'].mean().sort_values(ascending=False)
highest_profit_month = monthly_avg_profit.index[0]
print("--- 22. Month with Highest Average Profit ---")
print(f"Month Number: {highest_profit_month} (Average Profit: ${monthly_avg_profit.iloc[0]:,.2f})")
print("-" * 50)

# --- 23. Calculate the average delivery time (Ship Date - Order Date) by Region. ---
# 'Shipping Delay' column created in step 9
avg_delivery_time_region = df.groupby('Region')['Shipping Delay'].mean().dt.days.round(1)
print("--- 23. Average Delivery Time (Days) by Region ---")
print(avg_delivery_time_region)
print("-" * 50)

# --- 24. Identify the most profitable Item Type in each Region. ---
# Group by both Region and Item Type, find total profit, then get the Item Type with max profit in each Region
idx = df.groupby(['Region'])['Profit'].transform(max) == df['Profit']
df_max_profit = df[idx].drop_duplicates(subset=['Region'])[['Region', 'Item Type', 'Profit']]
df_max_profit_item = df.groupby(['Region', 'Item Type'])['Profit'].sum().reset_index()
most_profitable_item_per_region = df_max_profit_item.loc[df_max_profit_item.groupby('Region')['Profit'].idxmax()]
print("--- 24. Most Profitable Item Type in Each Region (by Total Profit) ---")
print(most_profitable_item_per_region.set_index('Region')[['Item Type', 'Profit']].round(2))
print("-" * 50)

# --- 25. Determine which Order Priority has the highest average Profit Margin. ---
priority_margin = df.groupby('Order Priority')['Profit Margin (%)'].mean().sort_values(ascending=False).round(2)
highest_margin_priority = priority_margin.index[0]
print("--- 25. Average Profit Margin (%) by Order Priority ---")
print(priority_margin)
print(f"\nHighest Average Profit Margin: '{highest_margin_priority}' ({priority_margin.iloc[0]}%)")
print("-" * 50)

# --- 26. Compare average delivery delay and profit between Online and Offline channels. ---
channel_comparison = df.groupby('Sales Channel').agg(
    Average_Delivery_Delay_Days=('Shipping Delay', lambda x: x.mean().days),
    Average_Profit=('Profit', 'mean')
).round(2)
print("--- 26. Comparison of Delay and Profit by Sales Channel ---")
print(channel_comparison)
print("-" * 50)

# --- 27. Export the final processed DataFrame (with new columns) to sales_summary.csv. ---
EXPORT_FILE_NAME = "sales_summary.csv"
df.to_csv(EXPORT_FILE_NAME, index=False)
print(f"--- 27. Final Processed DataFrame Exported to: '{EXPORT_FILE_NAME}' ---")